### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by shidhu40** [seantomburke/Dropbox-PHP-API#4]
Is there is any way to save files on my localhost directory

**Comment by hawaiianchimp** [comment]
Hey @shidhu40, I created this real quick for the Dropbox Hackathon in 2012. I mostly made it so I could understand OAuth 1.0 easier. I'm pretty sure, in fact I know, the Dropbox API has changed significantly since then, so this repository is probably not going to help you much. Sorry about that!
